version: '3'
services:
  postgres:
    image: postgres:11.4
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=dev_user
      - POSTGRES_PASSWORD=dev_password
      - POSTGRES_DB=authservice_dev
