"""empty message

Revision ID: 805ec9266db9
Revises: 
Create Date: 2019-08-21 11:49:11.019556

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '805ec9266db9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('firstname', sa.String(), nullable=False),
    sa.Column('middlename', sa.String(), nullable=True),
    sa.Column('lastname', sa.String(), nullable=False),
    sa.Column('suffix', sa.String(), nullable=True),
    sa.Column('ssn', sa.String(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('date_registered', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
